### ISSUE TITLE
Curious rounding behaviour

### ISSUE THREAD

**Issue by donovanhide** [woodsbury/decimal128#9] opened 2023-12-23 08:06 UTC
Hi,

firstly, thanks for this library, it is great!

Just wanted to point out this slightly perplexing comparison with another decimal library when flooring values:

https://go.dev/play/p/Ltr2fj4_TpC

Is there a rational explanation for this difference, or is it a bug?

Thanks!

**Comment by woodsbury** [comment] 2023-12-23 09:53
Hey

The current implementation for `FromFloat64` attempts to reproduce the value of the `float64` exactly. If you print the `float64` to more digits you should see they actually match. For example: https://go.dev/play/p/ZUn0UT5b9jz

I get that that can be surprising and sometimes not what you want. There are a few times where it can be what you want though, so it's tricky choosing a good common implementation. In some instances you can use `.Round` to round the result after the conversion to the number of digits you want, but that may not always to be easy to do. If you need to process a `float64` to only a specific number of digits then the simplest way at the moment is probably to print it to that level of precision with `fmt.Sprintf` and then parse it again using the `Parse` function.

My general advice though is to avoid as much as possible any conversions between decimal and binary floating point formats. Rewriting your first example but avoiding the `float64` shows the two libraries behaving the same: https://go.dev/play/p/_qQby2WyT5a

**Comment by woodsbury** [comment] 2023-12-27 22:31
Merry Christmas!

If your value is coming in in a JSON message, then going straight from the JSON to decimal is the best option to make sure no precision is lost. The library supports parsing JSON numbers, so if you have a struct you're parsing into you can just use the `Decimal` type for the fields. Alternatively you can use the standard library's `json.Number` type to get a string you can then use `Parse` on.

I have considered making an equivalent decimal64 library in the past. The most common use case for decimal values is financial calculations though and 128 bits is often what people want there.

**Comment by woodsbury** [comment] 2024-01-04 22:27
Unfortunately Go doesn't expose the JSON tags like `,string` to the marshalling functions, so there isn't a way to tell if you want quoted strings or not - those options only really work with the built in types that the JSON package supports internally. This behaviour can be changed by adding in your own custom marshalling functions though. For example:

https://play.golang.com/p/mAzJtVDD9Gg

In this example you would then use the `QuotedDecimal` type anywhere you were expecting or wanting to produce numbers with quotes around them, and the type can then be cast back to `decimal128.Decimal`.

**Comment by woodsbury** [comment] 2024-01-08 10:39
Yes, creating your own type can make using the values a little more difficult. And you're right that changing the behaviour now could be a breaking change.

On the plus side, the discussion around the `encoding/json/v2` seems like they're considering improving these things.

**Comment by prowley** [comment] 2024-02-22 02:09
The shopspring approach is to unmarshall both numbers and strings, but marshall to strings with a global flag if you want marshall to number.

**Comment by woodsbury** [comment] 2024-03-13 22:06
I'm going to close this because I think the original issue here has been resolved. The latest version of the module also has a couple of extra functions, `Frexp` and `Ldexp`, that can be used to control the precision of a decimal by shifting a number into a common base before rounding.

If and when v2 of the encoding/json package is available I will definitely be considering adopting any improvements it provides, including support for marshalling numbers as strings.

**Closed by woodsbury** 2024-03-13 22:06 UTC
